PSDK_HOME = C:\Program Files\Microsoft SDKs\Windows\v7.1
BOST_HOME = C:\boost_1_44_0
OSSL_HOME = C:\Program Files\OpenSSL-Win32


!IF "$(BUILD)" == ""
BUILD = debug
!ENDIF


!IF "$(BUILD)" == "release"

CL_OPTS = \
	/O2 \
	/Oi \
	/GL \
	/D "NODEBUG" \
	/FD \
	/Gy \
	/Zi

LINK_OPTS = \
	/INCREMENTAL:NO \
	/OPT:REF \
	/OPT:ICF \
	/LTCG \
	/NODEFAULTLIB:LIBCMT \
	libcmt.lib


!ELSEIF  "$(BUILD)" == "debug"

CL_OPTS = \
	/Od \
	/Gm \
	/D "_DEBUG" \
	/RTC1 \
	/ZI

LINK_OPTS = \
	/INCREMENTAL:NO \
	/DEBUG \
	/NODEFAULTLIB:LIBCMT \
	libcmtd.lib


!ENDIF




!IF "$(ARCH)" == ""
ARCH = x86
!ENDIF

!IF "$(ARCH)" == "x64"

LIB_ARCH_DIR = x64\

!ELSEIF  "$(ARCH)" == "x86"

LIB_ARCH_DIR = 

!ENDIF





all: \
	test.exe



test.exe: \
		test.obj
	LINK \
		/MACHINE:$(ARCH) \
		/OUT:"..\dist\test.exe" \
		/NOLOGO \
		/LIBPATH:"$(PSDK_HOME)\Lib$(LIB_ARCH_DIR)" \
		/LIBPATH:"$(BOST_HOME)\stage\lib" \
		$(LINK_OPTS) \
		..\dist\libmwebsockc.lib \
		user32.lib \
		advapi32.lib \
		Gdi32.lib \
		$**

.cpp.obj:
	CL \
		/D "WIN32" \
		/D "_CONSOLE" \
		/EHsc \
		/W3 \
		/nologo \
		/c \
		/TP \
		/I "..\include" \
		/I "$(PSDK_HOME)\Include" \
		/I "$(BOST_HOME)" \
		/I "$(OSSL_HOME)\include" \
		$(CL_OPTS) \
		$*.cpp


clean: clean_parts
	DEL /Q ..\dist\test.exe
	DEL /Q ..\dist\test.pdb

clean_parts:
	DEL /Q *.obj
	DEL /Q *.pdb
	DEL /Q *.idb
	DEL /Q *.res
	DEL /Q *.tlb

